### ISSUE TITLE
[BUG] Code gets stuck when cold-loading series pages

### ISSUE THREAD

**Issue by derpondus** [martian0x80/CrunchyComments#10]
### The Issue
- The first thing the plugin does on load is starting the `restoreComments` process, 
- For this, it has to check the release date, 
- Which it does by getting the `.release-date` html element 
- Which uses the same function as is used to wait for comentario to finish loading to inject the spoilers and timestamps
- This function is implemented to block until the element appears.
- But, since the series pages dont have this  element, we just wait indefinetely...

---

### Reproduction
1. Create a new Tab on Firefox
2. Go here: https://www.crunchyroll.com/de/series/GRMG8ZQZR/one-piece
**What happens:** No comment section
**What should happen:** Comment section

(also you can check this by going to `dev console` > `Debugger` > `Main-Thread` (or similar) > `content-script.js` and put a breakpoint at line `27` (`const elem = document.querySelector(selector)`). You should see the that the execution is repeatedly stopped, indicating an infinite loop of waiting)

---

### Fix-Suggestions
1. For now: always execute the restore comments process for series pages
2. Find alternative way to get a release date (e.g. something like first episode of earliest known season)

###  Can I work on this?
- [X] Yes

**Comment by martian0x80** [comment]
Haha, I literally saw this about the same time you did lol, and was talking about this with Lakshay.

**Comment by derpondus** [comment]
Fixed by 5cff20acc42e0488b4d140df4d639c5c32aed431

**Comment by derpondus** [comment]
Fixed by 5cff20acc42e0488b4d140df4d639c5c32aed431
