### ISSUE TITLE
Log in via GitHub not working

### ISSUE THREAD

**Issue by przemub** [martian0x80/CrunchyComments#16]
Hi,

First, it's a great idea - I've found it looking whether it already exists :)

I cannot login via GitHub. I get an error that `redirect_uri` is not configured for this application, so this should be an easy fix!

Here is the OAuth2 link I was sent to:
`https://github.com/login/oauth/authorize?client_id=Ov23litLgZjLw9JynboZ&redirect_uri=https%3A%2F%2Fchat.crunchycomments.com%2Fapi%2Foauth%2Fgithub%2Fcallback&response_type=code&scope=read%3Auser+user%3Aemail&state=XXX`

Best,
Prem

**Comment by martian0x80** [comment]
Thanks for the report @przemub
My comentario instance seems to be having a few problems with oauth recently after I moved everything to a new domain. Similar problem with X login. I'll see what I can do.

**Comment by martian0x80** [comment]
Fixed with ce0a733
