### ISSUE TITLE
Old comments

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [martian0x80/CrunchyComments#3]
according to this you access your backend api as found [here](https://github.com/martian0x80/CrunchyComments/blob/4104c2fb9b6d6590f32f92ae16eb73e2968d2b63/content-script.js#L73-L85)
but how are you loading all the old comments? where are you finding them??

**Comment by LakshayGMZ** [comment]
Hi @NeonGamerBot-QK ,
currently comment restore part is **close sourced**.
Feel free to contribute in the project
Thanks!!

**Comment by NeonGamerBot-QK** [comment]
> Hi @NeonGamerBot-QK , currently comment restore part is **close sourced**. Feel free to contribute in the project Thanks!!

im  not here for contributing? im talking about where the comments are being sourced from?

**Comment by NeonGamerBot-QK** [comment]
??

**Comment by NeonGamerBot-QK** [comment]
why did you close it? do you not want to respond where its being sourced from?

**Comment by LakshayGMZ** [comment]
I just told you above its not open sourced.

**Comment by NeonGamerBot-QK** [comment]
So since its not open source you dont wana disclose how your getting them?
