### ISSUE TITLE
Support Ratings on Show-level comments

### ISSUE THREAD

**Issue by cscherban** [martian0x80/CrunchyComments#7]
Hi! 

Love the project! Idk if you have a task management system, so posting a GH issue.

I think it would be great to add Star Ratings to the show-level comments. 

I haven't really looked at the source to see how difficult it is, would be willing to take this task too!

**Comment by martian0x80** [comment]
hey @cscherban 

We use Discord for feature suggestions and discussion, but issues are welcome as well.

I think upvotes/downvotes serve the same purpose as star ratings. And will require modifying the comentario source/fork.
